/*
 * Dlg_TEFMensagem.java
 *
 * Created on 11 de Setembro de 2007, 13:49
 */

package br.com.nfce.tef;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JDialog;

/**
 *
 * @author  supervisor
 */
public class Dlg_TEFMensagem extends javax.swing.JDialog {
  
  /** Creates new form Dlg_TEFMensagem */
  public Dlg_TEFMensagem() {
    super(new JDialog(), "Mensagem do TEF", true);
    try {
      initComponents();
      pack();
    } catch(Exception ex) {
      ex.printStackTrace();
    }
    try {
      this.setUndecorated(true);
    } catch (Exception exception) {
    }

    
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    jPanel1 = new javax.swing.JPanel();
    lbLinha3 = new javax.swing.JLabel();
    lbTitulo = new javax.swing.JLabel();
    lbLinha1 = new javax.swing.JLabel();
    lbLinha2 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    getContentPane().setLayout(new java.awt.GridBagLayout());

    jPanel1.setBackground(new java.awt.Color(255, 255, 200));
    jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
    jPanel1.setLayout(new java.awt.GridBagLayout());

    lbLinha3.setFont(new java.awt.Font("Dialog", 1, 22));
    lbLinha3.setText("Linha-3");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
    jPanel1.add(lbLinha3, gridBagConstraints);

    lbTitulo.setFont(new java.awt.Font("Dialog", 1, 15));
    lbTitulo.setText("Titulo");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
    jPanel1.add(lbTitulo, gridBagConstraints);

    lbLinha1.setFont(new java.awt.Font("Dialog", 0, 14));
    lbLinha1.setText("Linha-1");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
    jPanel1.add(lbLinha1, gridBagConstraints);

    lbLinha2.setFont(new java.awt.Font("Dialog", 0, 14));
    lbLinha2.setText("Linha-2");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
    jPanel1.add(lbLinha2, gridBagConstraints);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.weighty = 1.0;
    getContentPane().add(jPanel1, gridBagConstraints);
    setUndecorated(true);

    pack();
  }// </editor-fold>//GEN-END:initComponents
  
  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
	Dlg_TEFMensagem dialog = new Dlg_TEFMensagem();
	dialog.addWindowListener(new java.awt.event.WindowAdapter() {
	  public void windowClosing(java.awt.event.WindowEvent e) {
	    System.exit(0);
	  }
	});
	dialog.setVisible(true);
      }
    });
  }
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel jPanel1;
  public javax.swing.JLabel lbLinha1;
  public javax.swing.JLabel lbLinha2;
  public javax.swing.JLabel lbLinha3;
  public javax.swing.JLabel lbTitulo;
  // End of variables declaration//GEN-END:variables
  
  public void showMensagem(int iTEFTempoMensagem) {
     esperar( iTEFTempoMensagem );
     this.pack();

     Toolkit tk = Toolkit.getDefaultToolkit();
     Dimension d = tk.getScreenSize();
     int screenHeight = d.height;
     int screenWidth  = d.width;

     setLocation((screenWidth / 2) - this.getWidth() / 2, (screenHeight / 2) - this.getHeight() / 2);

     setVisible(true);
  }
  
  public void esperar(int iTEFTempoMens) {
    final Timer timer = new Timer();

    int delay   = iTEFTempoMens; // delay for (5000) msec.
    int period  = 1000; // repeat every sec.

    timer.schedule(new TimerTask() {
      public void run() {
        dispose();
        timer.cancel();
      }
    }, delay, period);
  }  
 
}
