package br.com.nfce.tef;

import java.awt.event.ActionEvent;
import javax.swing.AbstractAction;
import javax.swing.JComponent;
import javax.swing.KeyStroke;

/**
 * @author Cleber Moraes
 */
public class Frm_TEF_Operacoes extends javax.swing.JDialog {
  Cls_TEF_Dedicado td = null;
  Cls_TEF_ImpTrasacao imp_trans = null;
  
  char chSeparador = (java.io.File.separator).charAt(0);    //-- separador de path de diretorio --//
  
  /** Creates new form Frm_TEF_Operacoes */
  public Frm_TEF_Operacoes() {
    initComponents();
    
    td = new Cls_TEF_Dedicado();
    imp_trans = new Cls_TEF_ImpTrasacao(parent, td);
    
    td.tefVerificaOperacaoPendente(); //

    set_Separador();
    
    set_Moedas();
    
    getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke("ESCAPE"), "sair");
    getRootPane().getActionMap().put("sair", new AbstractAction("sair") {
      public void actionPerformed(ActionEvent evt) {
    	dispose();
      }
    });   
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    bgOper = new javax.swing.ButtonGroup();
    jTabbedPane1 = new javax.swing.JTabbedPane();
    pnVenda = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    frmDocumento = new javax.swing.JTextField();
    jLabel2 = new javax.swing.JLabel();
    frmValorTotal = new javax.swing.JTextField();
    jLabel3 = new javax.swing.JLabel();
    cbMoeda = new javax.swing.JComboBox();
    btnTransacaoComCartao = new javax.swing.JButton();
    btnTransacaoComCheque = new javax.swing.JButton();
    jPanel2 = new javax.swing.JPanel();
    jLabel4 = new javax.swing.JLabel();
    frmValorTotal_Canc = new javax.swing.JTextField();
    jLabel5 = new javax.swing.JLabel();
    frmNSUTransacao_Canc = new javax.swing.JTextField();
    jLabel6 = new javax.swing.JLabel();
    frmDataTransacao_Canc = new javax.swing.JTextField();
    jLabel7 = new javax.swing.JLabel();
    frmHoraTransacao_Canc = new javax.swing.JTextField();
    btnCancelar = new javax.swing.JButton();
    jPanel3 = new javax.swing.JPanel();
    jPanel5 = new javax.swing.JPanel();
    rdPreAutorizacaoCartao = new javax.swing.JRadioButton();
    rdPagamentoContaVisanet = new javax.swing.JRadioButton();
    rdPagamentoEncargosBanrisul = new javax.swing.JRadioButton();
    rdTransacaoEPharma = new javax.swing.JRadioButton();
    rdTransacaoInfocard = new javax.swing.JRadioButton();
    rdTransacaoEMS = new javax.swing.JRadioButton();
    btnExecutarOperacao = new javax.swing.JButton();
    jPanel4 = new javax.swing.JPanel();
    btnModoAdministrativo = new javax.swing.JButton();
    btnPedidoAutorizacaoCartao = new javax.swing.JButton();
    btnPedidoAutorizacaoCheque = new javax.swing.JButton();
    btnConfirmaOperacao = new javax.swing.JButton();
    btnNaoConfirmaOperacao = new javax.swing.JButton();
    jLabel8 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Operações de T.E.F.");
    getContentPane().setLayout(new java.awt.GridBagLayout());

    jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 13));

    pnVenda.setLayout(new java.awt.GridBagLayout());

    jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13));
    jLabel1.setText("Docto. Vinculado:");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    pnVenda.add(jLabel1, gridBagConstraints);

    frmDocumento.setFont(new java.awt.Font("Tahoma", 1, 13));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.ipadx = 80;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.weighty = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
    pnVenda.add(frmDocumento, gridBagConstraints);

    jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13));
    jLabel2.setText("Valor Total:");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
    pnVenda.add(jLabel2, gridBagConstraints);

    frmValorTotal.setFont(new java.awt.Font("Tahoma", 1, 13));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.ipadx = 80;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.weighty = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
    pnVenda.add(frmValorTotal, gridBagConstraints);

    jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13));
    jLabel3.setText("Moeda:");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
    pnVenda.add(jLabel3, gridBagConstraints);

    cbMoeda.setFont(new java.awt.Font("Tahoma", 1, 13));
    cbMoeda.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.weighty = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
    pnVenda.add(cbMoeda, gridBagConstraints);

    btnTransacaoComCartao.setFont(new java.awt.Font("Tahoma", 1, 13));
    btnTransacaoComCartao.setText("Realiza Transacao com Cartao");
    btnTransacaoComCartao.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnTransacaoComCartaoActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.weighty = 1.0;
    pnVenda.add(btnTransacaoComCartao, gridBagConstraints);

    btnTransacaoComCheque.setFont(new java.awt.Font("Tahoma", 1, 13));
    btnTransacaoComCheque.setText("Realiza Transacao com Cheque");
    btnTransacaoComCheque.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnTransacaoComChequeActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.weighty = 1.0;
    pnVenda.add(btnTransacaoComCheque, gridBagConstraints);

    jTabbedPane1.addTab("Venda:", pnVenda);

    jPanel2.setLayout(new java.awt.GridBagLayout());

    jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13));
    jLabel4.setText("Valor Total:");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
    jPanel2.add(jLabel4, gridBagConstraints);

    frmValorTotal_Canc.setFont(new java.awt.Font("Tahoma", 1, 13));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.ipadx = 80;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.weighty = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
    jPanel2.add(frmValorTotal_Canc, gridBagConstraints);

    jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13));
    jLabel5.setText("Nr. da Transacao:");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
    jPanel2.add(jLabel5, gridBagConstraints);

    frmNSUTransacao_Canc.setFont(new java.awt.Font("Tahoma", 1, 13));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.ipadx = 90;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.weighty = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
    jPanel2.add(frmNSUTransacao_Canc, gridBagConstraints);

    jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13));
    jLabel6.setText("Data:");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
    jPanel2.add(jLabel6, gridBagConstraints);

    frmDataTransacao_Canc.setFont(new java.awt.Font("Tahoma", 1, 13));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.ipadx = 80;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.weighty = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
    jPanel2.add(frmDataTransacao_Canc, gridBagConstraints);

    jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13));
    jLabel7.setText("Hora:");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
    jPanel2.add(jLabel7, gridBagConstraints);

    frmHoraTransacao_Canc.setFont(new java.awt.Font("Tahoma", 1, 13));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.ipadx = 50;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.weighty = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
    jPanel2.add(frmHoraTransacao_Canc, gridBagConstraints);

    btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 13));
    btnCancelar.setText("Cancela a Transacao");
    btnCancelar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnCancelarActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.weighty = 1.0;
    jPanel2.add(btnCancelar, gridBagConstraints);

    jTabbedPane1.addTab("Cancelamento:", jPanel2);

    jPanel3.setLayout(new java.awt.GridBagLayout());

    jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Selecione uma operação:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13)));
    jPanel5.setFont(new java.awt.Font("Tahoma", 1, 13));
    jPanel5.setLayout(new java.awt.GridBagLayout());

    bgOper.add(rdPreAutorizacaoCartao);
    rdPreAutorizacaoCartao.setFont(new java.awt.Font("Tahoma", 1, 13));
    rdPreAutorizacaoCartao.setText("Pre-Autorizacao de cartao de credito");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    jPanel5.add(rdPreAutorizacaoCartao, gridBagConstraints);

    bgOper.add(rdPagamentoContaVisanet);
    rdPagamentoContaVisanet.setFont(new java.awt.Font("Tahoma", 1, 13));
    rdPagamentoContaVisanet.setText("Pagamento de contas Visanet");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    jPanel5.add(rdPagamentoContaVisanet, gridBagConstraints);

    bgOper.add(rdPagamentoEncargosBanrisul);
    rdPagamentoEncargosBanrisul.setFont(new java.awt.Font("Tahoma", 1, 13));
    rdPagamentoEncargosBanrisul.setText("Pagamento de encargos Banrisul");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    jPanel5.add(rdPagamentoEncargosBanrisul, gridBagConstraints);

    bgOper.add(rdTransacaoEPharma);
    rdTransacaoEPharma.setFont(new java.awt.Font("Tahoma", 1, 13));
    rdTransacaoEPharma.setText("Transacao de consulta e vendas E-Pharma");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    jPanel5.add(rdTransacaoEPharma, gridBagConstraints);

    bgOper.add(rdTransacaoInfocard);
    rdTransacaoInfocard.setFont(new java.awt.Font("Tahoma", 1, 13));
    rdTransacaoInfocard.setText("Transacoes Infocard");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    jPanel5.add(rdTransacaoInfocard, gridBagConstraints);

    bgOper.add(rdTransacaoEMS);
    rdTransacaoEMS.setFont(new java.awt.Font("Tahoma", 1, 13));
    rdTransacaoEMS.setText("Transcoes EMS");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 5;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    jPanel5.add(rdTransacaoEMS, gridBagConstraints);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.weighty = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(3, 5, 0, 5);
    jPanel3.add(jPanel5, gridBagConstraints);

    btnExecutarOperacao.setFont(new java.awt.Font("Tahoma", 1, 13));
    btnExecutarOperacao.setText("Executar");
    btnExecutarOperacao.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnExecutarOperacaoActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
    jPanel3.add(btnExecutarOperacao, gridBagConstraints);

    jTabbedPane1.addTab("Operações:", jPanel3);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.weighty = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
    getContentPane().add(jTabbedPane1, gridBagConstraints);

    jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Operações do Gerenciador Padrão:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13)));
    jPanel4.setLayout(new java.awt.GridBagLayout());

    btnModoAdministrativo.setFont(new java.awt.Font("Dialog", 1, 13));
    btnModoAdministrativo.setMnemonic('m');
    btnModoAdministrativo.setText("Modo Administrativo");
    btnModoAdministrativo.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnModoAdministrativoActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
    jPanel4.add(btnModoAdministrativo, gridBagConstraints);

    btnPedidoAutorizacaoCartao.setFont(new java.awt.Font("Dialog", 1, 13));
    btnPedidoAutorizacaoCartao.setText("Autorizacao para Cartao");
    btnPedidoAutorizacaoCartao.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnPedidoAutorizacaoCartaoActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(6, 5, 0, 5);
    jPanel4.add(btnPedidoAutorizacaoCartao, gridBagConstraints);

    btnPedidoAutorizacaoCheque.setFont(new java.awt.Font("Dialog", 1, 13));
    btnPedidoAutorizacaoCheque.setText("Autorizacao para Cheque");
    btnPedidoAutorizacaoCheque.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnPedidoAutorizacaoChequeActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(6, 5, 0, 5);
    jPanel4.add(btnPedidoAutorizacaoCheque, gridBagConstraints);

    btnConfirmaOperacao.setFont(new java.awt.Font("Dialog", 1, 13));
    btnConfirmaOperacao.setText("Confirma Operacao");
    btnConfirmaOperacao.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnConfirmaOperacaoActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(6, 5, 0, 5);
    jPanel4.add(btnConfirmaOperacao, gridBagConstraints);

    btnNaoConfirmaOperacao.setFont(new java.awt.Font("Dialog", 1, 13));
    btnNaoConfirmaOperacao.setText("Nao Confirma Operacao");
    btnNaoConfirmaOperacao.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnNaoConfirmaOperacaoActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(6, 5, 5, 5);
    jPanel4.add(btnNaoConfirmaOperacao, gridBagConstraints);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.ipadx = 40;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.weighty = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
    getContentPane().add(jPanel4, gridBagConstraints);

    jLabel8.setText("<Esc> - Sair");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
    getContentPane().add(jLabel8, gridBagConstraints);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btnTransacaoComCartaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransacaoComCartaoActionPerformed
    // TODO add your handling code here:
    transacaoComCartao();
  }//GEN-LAST:event_btnTransacaoComCartaoActionPerformed

  private void btnTransacaoComChequeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransacaoComChequeActionPerformed
    // TODO add your handling code here:
    transacaoComCheque();    
  }//GEN-LAST:event_btnTransacaoComChequeActionPerformed

  private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
    // TODO add your handling code here:
    cancelarTransacao();    
  }//GEN-LAST:event_btnCancelarActionPerformed

  private void btnExecutarOperacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExecutarOperacaoActionPerformed
    // TODO add your handling code here:
    executarOperacao();    
  }//GEN-LAST:event_btnExecutarOperacaoActionPerformed

  private void btnModoAdministrativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModoAdministrativoActionPerformed
    // TODO add your handling code here:
    modoAdministrativo();    
  }//GEN-LAST:event_btnModoAdministrativoActionPerformed

  private void btnPedidoAutorizacaoCartaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedidoAutorizacaoCartaoActionPerformed
    // TODO add your handling code here:
    pedidoAutorizacaoCartao();    
  }//GEN-LAST:event_btnPedidoAutorizacaoCartaoActionPerformed

  private void btnPedidoAutorizacaoChequeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedidoAutorizacaoChequeActionPerformed
    // TODO add your handling code here:
    pedidoAutorizacaoCheque();    
  }//GEN-LAST:event_btnPedidoAutorizacaoChequeActionPerformed

  private void btnConfirmaOperacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmaOperacaoActionPerformed
    // TODO add your handling code here:
    confirmaOperacao();    
  }//GEN-LAST:event_btnConfirmaOperacaoActionPerformed

  private void btnNaoConfirmaOperacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNaoConfirmaOperacaoActionPerformed
    // TODO add your handling code here:
    naoConfirmaOperacao();    
  }//GEN-LAST:event_btnNaoConfirmaOperacaoActionPerformed
 
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.ButtonGroup bgOper;
  private javax.swing.JButton btnCancelar;
  private javax.swing.JButton btnConfirmaOperacao;
  private javax.swing.JButton btnExecutarOperacao;
  private javax.swing.JButton btnModoAdministrativo;
  private javax.swing.JButton btnNaoConfirmaOperacao;
  private javax.swing.JButton btnPedidoAutorizacaoCartao;
  private javax.swing.JButton btnPedidoAutorizacaoCheque;
  private javax.swing.JButton btnTransacaoComCartao;
  private javax.swing.JButton btnTransacaoComCheque;
  private javax.swing.JComboBox cbMoeda;
  private javax.swing.JTextField frmDataTransacao_Canc;
  private javax.swing.JTextField frmDocumento;
  private javax.swing.JTextField frmHoraTransacao_Canc;
  private javax.swing.JTextField frmNSUTransacao_Canc;
  private javax.swing.JTextField frmValorTotal;
  private javax.swing.JTextField frmValorTotal_Canc;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JPanel jPanel4;
  private javax.swing.JPanel jPanel5;
  private javax.swing.JTabbedPane jTabbedPane1;
  private javax.swing.JPanel pnVenda;
  private javax.swing.JRadioButton rdPagamentoContaVisanet;
  private javax.swing.JRadioButton rdPagamentoEncargosBanrisul;
  private javax.swing.JRadioButton rdPreAutorizacaoCartao;
  private javax.swing.JRadioButton rdTransacaoEMS;
  private javax.swing.JRadioButton rdTransacaoEPharma;
  private javax.swing.JRadioButton rdTransacaoInfocard;
  // End of variables declaration//GEN-END:variables
  
  private void set_Separador() {
    chSeparador = (java.io.File.separator).charAt(0);
  }
  
  private void set_Moedas() {
    cbMoeda.setFont(new java.awt.Font("Dialog", 1, 13));
    cbMoeda.setForeground(new java.awt.Color(0, 0, 230));
    cbMoeda.removeAllItems();
    cbMoeda.addItem("Real");
    cbMoeda.addItem("Dolar");
  }
  
  private void transacaoComCartao() {
    // ---> Busca os valores e passa para as variaveis do TEFFlex
    td.sTEFValorTotal = frmValorTotal.getText().trim();

    if (!td.sTEFValorTotal.equals("")) {
      td.tefLimpaVariaveis();
      td.tefVerificaOperacaoPendente();
      td.sTEFDoctoVinculado = frmDocumento.getText();
      td.sTEFValorTotal     = frmValorTotal.getText();
      td.sTEFMoeda          = String.valueOf( cbMoeda.getSelectedItem() );

      if (td.sTEFMoeda.equals("Real"))
        td.sTEFMoeda = "0";

      if (td.sTEFMoeda.equals("Dolar"))
        td.sTEFMoeda = "1";

      // ---> Executa a funcao
      td.tefVendaCartao();

      if (td.sTEFRetorno.equals("0")) {
        // ---> Neste ponto chame a sua fun‡Æo para imprimir o comprovante
        //      Se a impressÆo foi Ok, sua fun‡Æo deve retornar '0' em sTEFRetorno
        imp_trans.TEFImprimeTransacao("R", "", "", "");
        //
        if (td.sTEFRetorno.equals("0"))
           td.tefFechaOperacao();
         else
           td.tefNaoConfirmaOperacao();
       }
     } else {
       javax.swing.JOptionPane.showMessageDialog(null, "Informe os detalhes da transacao!",
                                                 "Erro:", javax.swing.JOptionPane.ERROR_MESSAGE);
     }
  }
  
  private void transacaoComCheque() {
    // ---> Busca os valores e passa para as vari veis do TEFFlex
    td.sTEFValorTotal = frmValorTotal.getText();

    if (!td.sTEFValorTotal.equals("")) {
      td.tefLimpaVariaveis();
      td.tefVerificaOperacaoPendente();
      td.sTEFDoctoVinculado = frmDocumento.getText();
      td.sTEFValorTotal = frmValorTotal.getText();
      // ---> Executa a funcao
      td.tefVendaCheque();
      if (td.sTEFRetorno.equals("0")) {
        //
        // ---> Neste ponto chame a sua fun‡Æo para imprimir o comprovante
        //      Se a impressÆo foi Ok, sua fun‡Æo deve retornar '0' em sTEFRetorno

        imp_trans.TEFImprimeTransacao("R", "", "", "");

        //
        if (td.sTEFRetorno.equals("0"))
          td.tefFechaOperacao();
        else
          td.tefNaoConfirmaOperacao();
      }
    } else {
      javax.swing.JOptionPane.showMessageDialog(null, "Informe os detalhes da transacao!",
                                    "Erro:", javax.swing.JOptionPane.ERROR_MESSAGE);
      pnVenda.transferFocus();    //send Activate to (tpVenda(tdValores(self)))
    }
  }
  
  private void cancelarTransacao() {
    // ---> Busca os valores e passa para as vari veis do TEFFlex
    td.sTEFValorTotal = frmValorTotal_Canc.getText();

    if (!td.sTEFValorTotal.equals("")) {
      td.tefLimpaVariaveis();
      td.tefVerificaOperacaoPendente();

      td.sTEFValorTotal    = frmValorTotal_Canc   .getText();
      td.sTEFnsuTransacao  = frmNSUTransacao_Canc .getText();
      td.sTEFdataTransacao = frmDataTransacao_Canc.getText();
      td.sTEFhoraTransacao = frmHoraTransacao_Canc.getText();

        // ---> Executa a funcao
        td.tefCancelaTransacao();
        if (td.sTEFRetorno.equals("0")) {
          //
          // ---> Neste ponto chame a sua funcao para imprimir o comprovante
          //      Se a impressao foi Ok, sua funcao deve retornar '0' em sTEFRetorno
          imp_trans.TEFImprimeTransacao("R", "", "", "");
          //
            if (td.sTEFRetorno.equals("0"))
              td.tefFechaOperacao();
            else
              td.tefNaoConfirmaOperacao();
        }
    } else {
      javax.swing.JOptionPane.showMessageDialog(null, "Informe os detalhes da transacao!",
                                    "Erro:", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
  }  
  
  private void executarOperacao() {
    //----> Preparacao de dados para SITEF
    // Close_output channel 5
    //----> Fim

    int iOperacao = 0;
    String sOperacao = "";

    //  iOperacao = Current_Radio of (rgOutrasOperacoes(tpOutrasOperacoes(Self))) to

    if (rdPreAutorizacaoCartao     .isSelected()) sOperacao =  "PRE";  //1
    if (rdPagamentoContaVisanet    .isSelected()) sOperacao =  "PGV";  //2
    if (rdPagamentoEncargosBanrisul.isSelected()) sOperacao =  "PGB";  //3
    if (rdTransacaoEPharma         .isSelected()) sOperacao =  "EPH";  //4
    if (rdTransacaoInfocard        .isSelected()) sOperacao =  "INF";  //5
    if (rdTransacaoEMS             .isSelected()) sOperacao =  "EMS";  //6

    td.sTEFValorTotal = frmValorTotal.getText();

    if (!td.sTEFValorTotal.equals("")) {
      td.tefLimpaVariaveis();
      td.tefVerificaOperacaoPendente();
      td.sTEFValorTotal = frmValorTotal.getText();

      td.tefGravaOperacao(sOperacao);  // ---> Executa a funcao
      if (td.sTEFRetorno.equals("0"))
        td.tefConfirmaOperacao();
      if (td.sTEFRetorno.equals("0")) {

        //
        //
        //
        imp_trans.TEFImprimeTransacao("R", "", "", "");

        if (td.sTEFRetorno.equals("0"))
          td.tefFechaOperacao();
        else
          td.tefNaoConfirmaOperacao();
      }
    } else {
      javax.swing.JOptionPane.showMessageDialog(null, "Informe os detalhes da transacao!",
                                    "Erro:", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
  }
  
  private void modoAdministrativo() {
    td.tefLimpaVariaveis();
    td.tefVerificaOperacaoPendente();

    td.tefModoAdministrativo();
    if (td.sTEFRetorno.equals("0")) {
      //
      // ---> Neste ponto chame a sua funcao para imprimir o comprovante
      //      Se a impressÆo foi Ok, sua funcao deve retornar '0' em sTEFRetorno
      //
      imp_trans.TEFImprimeTransacao("R", "", "", "");

      if (td.sTEFRetorno.equals("0"))
        td.tefFechaOperacao();
      else
        td.tefNaoConfirmaOperacao();
    }
  }  

  private void pedidoAutorizacaoCartao() {
    td.tefLimpaVariaveis();
    td.tefVerificaOperacaoPendente();
    // ---> Busca os valores e passa para as vari veis do TEFFlex

    td.sTEFDoctoVinculado = frmDocumento.getText();
    td.sTEFValorTotal     = frmValorTotal.getText();
    td.sTEFMoeda          = String.valueOf(cbMoeda.getSelectedItem());

    if (td.sTEFMoeda.equals("Real"))    // ---> Tratamento dos valores para o padrao VDFTEF
      td.sTEFMoeda = "0";

    if (td.sTEFMoeda.equals("Dolar"))
      td.sTEFMoeda = "1";

    td.tefPedidoAutorizacaoCartao();
  }  
  
  private void pedidoAutorizacaoCheque() {
    td.tefLimpaVariaveis();
    td.tefVerificaOperacaoPendente();

    // ---> Busca os valores e passa para as vari veis do TEFFlex
    td.sTEFDoctoVinculado = frmDocumento.getText();
    td.sTEFValorTotal     = frmValorTotal.getText();
    td.tefPedidoAutorizacaoCheque();
  }
  
  private void confirmaOperacao() {
    td.tefLimpaVariaveis();
    td.tefVerificaOperacaoPendente();

    td.tefConfirmaOperacao();

    if (td.sTEFRetorno.equals("0"))
      td.tefFechaOperacao();
  }
  
  private void naoConfirmaOperacao() {
    td.tefLimpaVariaveis();
    td.tefVerificaOperacaoPendente();

    td.tefNaoConfirmaOperacao();
  }  
  
}
